//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcquisitionRecord
    {
        public int Id { get; set; }
        public string DataUrl { get; set; }
        public int DataTypeId { get; set; }
        public System.DateTime AcquisitionTime { get; set; }
        public Nullable<System.DateTime> ReceptionTime { get; set; }
        public string Remark { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
