//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatrolReport
    {
        public int Id { get; set; }
        public string DefectTypeId { get; set; }
        public string EmergenceId { get; set; }
        public int TownShipId { get; set; }
        public string Village { get; set; }
        public int PatrolPointId { get; set; }
        public int PatrolRouteId { get; set; }
        public System.DateTime ReportTime { get; set; }
    
        public virtual TownShip TownShip { get; set; }
        public virtual PatrolPoint PatrolPoint { get; set; }
        public virtual Dictionary Dictionary { get; set; }
        public virtual PatrolRoute PatrolRoute { get; set; }
    }
}
