//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatrolScheme
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public int DefectTypeId { get; set; }
        public int EmployeeId { get; set; }
        public int PatrolRouteId { get; set; }
        public System.DateTime SchemeDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PatrolRoute PatrolRoute { get; set; }
    }
}
